// Generated by generate_gbk_font.py. Do not edit manually.
// Glyph byte layout: column-lsb
#ifndef LONGYIN_COLUMN_LSB_FONT_DATA_H
#define LONGYIN_COLUMN_LSB_FONT_DATA_H

#include <stddef.h>
#include <stdint.h>

#define FONT_WIDTH 16
#define FONT_HEIGHT 16
#define LONGYIN_COLUMN_LSB_FONT_TOTAL_COUNT 20902
#define LONGYIN_COLUMN_LSB_FONT_BYTES 32
#define LONGYIN_COLUMN_LSB_FIRST_UNICODE 0x4E00u
#define LONGYIN_COLUMN_LSB_LAST_UNICODE 0x9FA5u
#define LONGYIN_COLUMN_LSB_GLYPH_FORMAT "column-lsb"
#define LONGYIN_COLUMN_LSB_GLYPH_FORMAT_COLUMN_LSB 1
#define LONGYIN_COLUMN_LSB_BIT_ORDER_LSB_FIRST 1
#define LONGYIN_COLUMN_LSB_STORAGE_COLUMN_MAJOR 1
#define LONGYIN_COLUMN_LSB_STORAGE_ROW_MAJOR 0
#define LONGYIN_COLUMN_LSB_BIT0_IS_TOP_OR_LEFT 1
#define LONGYIN_COLUMN_LSB_UNICODE_TO_GBK_BYTES 2
#define LONGYIN_COLUMN_LSB_UNICODE_TO_GBK_COUNT 20902
#define LONGYIN_COLUMN_LSB_FONT_DATA_SIZE (20902u * 32u)
#define LONGYIN_COLUMN_LSB_GLYPH_OFFSET(unicode) (((size_t)((unicode) - LONGYIN_COLUMN_LSB_FIRST_UNICODE)) * LONGYIN_COLUMN_LSB_FONT_BYTES)

typedef struct {
    const uint8_t *data;
    size_t data_size;
    uint32_t first_unicode;
    uint32_t last_unicode;
    uint32_t glyph_count;
    uint32_t glyph_bytes;
    const char *format;
} longyin_column_lsb_font_info_t;

extern const uint8_t _binary_longyin_column_lsb_unicode_to_gbk_bin_start[];
extern const uint8_t _binary_longyin_column_lsb_unicode_to_gbk_bin_end[];
extern const uint8_t _binary_longyin_column_lsb_font_data_bin_start[];
extern const uint8_t _binary_longyin_column_lsb_font_data_bin_end[];

#define longyin_column_lsb_unicode_to_gbk ((const uint8_t *)_binary_longyin_column_lsb_unicode_to_gbk_bin_start)
#define longyin_column_lsb_font_data _binary_longyin_column_lsb_font_data_bin_start
#define longyin_column_lsb_unicode_to_gbk_size ((size_t)(_binary_longyin_column_lsb_unicode_to_gbk_bin_end - _binary_longyin_column_lsb_unicode_to_gbk_bin_start))
#define longyin_column_lsb_font_data_size ((size_t)(_binary_longyin_column_lsb_font_data_bin_end - _binary_longyin_column_lsb_font_data_bin_start))
#define longyin_column_lsb_glyph(unicode) (longyin_column_lsb_font_data + LONGYIN_COLUMN_LSB_GLYPH_OFFSET(unicode))

#endif /* LONGYIN_COLUMN_LSB_FONT_DATA_H */
