/**
 * @file font_service_version.h
 * @brief Version definitions for font_service (auto-generated)
 *
 * This file is automatically generated by version_manager component.
 * Do not modify manually!
 */

#ifndef FONT_SERVICE_VERSION_H
#define FONT_SERVICE_VERSION_H

#define FONT_SERVICE_VERSION_MAJOR    1
#define FONT_SERVICE_VERSION_MINOR    3
#define FONT_SERVICE_VERSION_PATCH    94
#define FONT_SERVICE_VERSION_STRING   "1.3.094"

#endif // FONT_SERVICE_VERSION_H
